version: '2'

services:
    nginx:
        image: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./conf/nginx/conf.d/:/etc/nginx/conf.d/:rw
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./conf/nginx/enable-php.conf:/etc/nginx/enable-php.conf:ro
            - ./log/nginx/:/var/log/nginx/:rw
            - /mnt/:/mnt/:rw
        links:
            - php72:fpm

    php72:
        build: ./php/php72/
        restart: always
        expose:
            - "9000"
        volumes:
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ./log/php-fpm/:/var/log/php-fpm/:rw
            - /mnt/:/mnt/:rw
            - /tmp/:/tmp/:rw
        links:
            - mysql:mysql
            - redis:redis

    mysql:
        image: mysql:latest
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
            - /mnt/data:/mnt/data:rw
            - /tmp/:/tmp/:rw
            - ./log/mysql/:/usr/local/mysql/:rw
        environment:
            MYSQL_ROOT_PASSWORD: "123456"

    redis:
        image: redis:latest
        restart: always
        volumes:
            - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
            - /mnt/redis.log:/mnt/redis.log:rw
            - /mnt/:/mnt/:rw
        ports:
            - "6379:6379"
        command: "redis-server /usr/local/etc/redis/redis.conf"