version: '2'

services:
    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./conf/nginx/conf.d:/etc/nginx/conf.d/
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/nginx/enable-php.conf:/etc/nginx/enable-php.conf
            - ./log/nginx/:/var/log/nginx/
            - /mnt/:/mnt/
        links:
            - php72:fpm

    php72:
        build: ./php/php72/
        restart: always
        expose:
            - "9000"
        volumes:
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini
            - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./log/php-fpm/:/var/log/php-fpm/
            - /mnt/:/mnt/
            - /tmp/:/tmp/
        links:
            - mysql:mysql
            - redis:redis

    mysql:
        image: mysql:latest
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./conf/mysql/my.cnf:/etc/mysql/my.cnf
            - /mnt/:/mnt/
            - ./log/mysql/:/var/log/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: "123456"

    redis:
        image: redis:latest
        restart: always
        volumes:
            - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
            - /mnt/redis.log:/mnt/redis.log
            - /mnt/:/mnt/
        ports:
            - "6379:6379"
        command: "redis-server /usr/local/etc/redis/redis.conf"